import { CRUD_RESOURCE_SCHEMA_MAP } from './crudResourceSchema';

export type JavaFieldType =
  | 'String'
  | 'Integer'
  | 'Long'
  | 'BigDecimal'
  | 'LocalDateTime';

export interface CrudField {
  name: string;
  type: JavaFieldType;
}

export interface CrudModule {
  resource: string;
  name: string;
  group: '基础资料' | '库存业务' | '系统管理';
  fields: CrudField[];
  tableFields?: CrudField[];
  searchFields?: CrudField[];
}

export const CRUD_MODULES: CrudModule[] = [
  {
    resource: 'brand',
    name: '品牌表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'image', type: 'String' },
      { name: 'content', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'series',
    name: '商品系列表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'content', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'maker',
    name: 'メーカー表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'goodsType',
    name: '商品分类表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'goods',
    name: '商品表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'sku', type: 'String' },
      { name: 'seriesId', type: 'Long' },
      { name: 'brandId', type: 'Long' },
      { name: 'typeId', type: 'Long' },
      { name: 'makerId', type: 'Long' },
      { name: 'price', type: 'BigDecimal' },
      { name: 'discount', type: 'BigDecimal' },
      { name: 'status', type: 'Integer' },
      { name: 'newPrice', type: 'BigDecimal' },
      { name: 'priceUpdateTime', type: 'LocalDateTime' },
      { name: 'images', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'isHot', type: 'Integer' },
      { name: 'version', type: 'Long' },
    ],
  },
  {
    resource: 'warehouse',
    name: '仓库表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'code', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'managerId', type: 'Long' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'customerLevel',
    name: '客户等级表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'discount', type: 'BigDecimal' },
      { name: 'remark', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'customer',
    name: '客户表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'customerCode', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'contactPerson', type: 'String' },
      { name: 'phone', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'country', type: 'String' },
      { name: 'city', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'levelId', type: 'Integer' },
      { name: 'remark', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'dept',
    name: '部门表',
    group: '基础资料',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'parentId', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'code', type: 'String' },
      { name: 'leaderId', type: 'Long' },
      { name: 'sort', type: 'Integer' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'stock',
    name: '商品库存表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'goodsId', type: 'Integer' },
      { name: 'goodsName', type: 'String' },
      { name: 'sku', type: 'String' },
      { name: 'warehouseId', type: 'Integer' },
      { name: 'currentQty', type: 'Integer' },
      { name: 'lockQty', type: 'Integer' },
      { name: 'price', type: 'BigDecimal' },
      { name: 'priceUpdateTime', type: 'LocalDateTime' },
      { name: 'status', type: 'Integer' },
      { name: 'version', type: 'Long' },
    ],
  },
  {
    resource: 'stockRecord',
    name: '库存流水表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'bizNo', type: 'String' },
      { name: 'orderId', type: 'Long' },
      { name: 'orderItemId', type: 'Long' },
      { name: 'stockId', type: 'Long' },
      { name: 'goodsId', type: 'Long' },
      { name: 'sku', type: 'String' },
      { name: 'goodsName', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'brandId', type: 'Long' },
      { name: 'brandName', type: 'String' },
      { name: 'seriesId', type: 'Long' },
      { name: 'seriesName', type: 'String' },
      { name: 'typeId', type: 'Long' },
      { name: 'typeName', type: 'String' },
      { name: 'makerId', type: 'Long' },
      { name: 'makerName', type: 'String' },
      { name: 'warehouseId', type: 'Long' },
      { name: 'beforeQty', type: 'Integer' },
      { name: 'changeQty', type: 'Integer' },
      { name: 'afterQty', type: 'Integer' },
      { name: 'type', type: 'Integer' },
      { name: 'sourceType', type: 'Integer' },
      { name: 'price', type: 'BigDecimal' },
      { name: 'priceUpdateTime', type: 'LocalDateTime' },
      { name: 'customerId', type: 'Long' },
      { name: 'customerName', type: 'String' },
      { name: 'requesterId', type: 'Long' },
      { name: 'requesterName', type: 'String' },
      { name: 'operatorId', type: 'Long' },
      { name: 'operatorName', type: 'String' },
      { name: 'remark', type: 'String' },
    ],
  },
  {
    resource: 'stockOrder',
    name: '库存业务单',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'orderNo', type: 'String' },
      { name: 'type', type: 'Integer' },
      { name: 'warehouseId', type: 'Long' },
      { name: 'sourceType', type: 'Integer' },
      { name: 'sourceId', type: 'Long' },
      { name: 'totalQty', type: 'Integer' },
      { name: 'state', type: 'Integer' },
      { name: 'requesterId', type: 'Long' },
      { name: 'requesterName', type: 'String' },
      { name: 'operatorId', type: 'Long' },
      { name: 'operatorName', type: 'String' },
      { name: 'remark', type: 'String' },
      { name: 'approverId', type: 'Long' },
      { name: 'approverName', type: 'String' },
      { name: 'approveTime', type: 'LocalDateTime' },
      { name: 'finishTime', type: 'LocalDateTime' },
    ],
  },
  {
    resource: 'stockOrderItem',
    name: '库存单明细',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'orderId', type: 'Long' },
      { name: 'goodsId', type: 'Long' },
      { name: 'sku', type: 'String' },
      { name: 'goodsName', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'brandId', type: 'Long' },
      { name: 'brandName', type: 'String' },
      { name: 'seriesId', type: 'Long' },
      { name: 'seriesName', type: 'String' },
      { name: 'typeId', type: 'Long' },
      { name: 'typeName', type: 'String' },
      { name: 'makerId', type: 'Long' },
      { name: 'makerName', type: 'String' },
      { name: 'beforeQty', type: 'Integer' },
      { name: 'changeQty', type: 'Integer' },
      { name: 'afterQty', type: 'Integer' },
      { name: 'price', type: 'BigDecimal' },
      { name: 'remark', type: 'String' },
    ],
  },
  {
    resource: 'priceRecord',
    name: '价格记录表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'goodsId', type: 'Long' },
      { name: 'goodsName', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'sku', type: 'String' },
      { name: 'oldPrice', type: 'BigDecimal' },
      { name: 'newPrice', type: 'BigDecimal' },
      { name: 'discount', type: 'BigDecimal' },
      { name: 'priceUpdateTime', type: 'LocalDateTime' },
      { name: 'operatorId', type: 'Long' },
      { name: 'operatorName', type: 'String' },
    ],
  },
  {
    resource: 'requestForm',
    name: '请求书表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'bizNo', type: 'String' },
      { name: 'userId', type: 'Long' },
      { name: 'username', type: 'String' },
      { name: 'deptId', type: 'Long' },
      { name: 'deptName', type: 'String' },
      { name: 'customerId', type: 'Long' },
      { name: 'customerName', type: 'String' },
      { name: 'warehouseId', type: 'Long' },
      { name: 'totalQty', type: 'Integer' },
      { name: 'requestQty', type: 'Integer' },
      { name: 'state', type: 'Integer' },
      { name: 'approverId', type: 'Long' },
      { name: 'approveName', type: 'String' },
      { name: 'approveTime', type: 'LocalDateTime' },
      { name: 'approveRemark', type: 'String' },
    ],
  },
  {
    resource: 'requestItem',
    name: '请求书商品明细表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'requestId', type: 'Long' },
      { name: 'goodsId', type: 'Long' },
      { name: 'sku', type: 'String' },
      { name: 'goodsName', type: 'String' },
      { name: 'englishName', type: 'String' },
      { name: 'brandId', type: 'Long' },
      { name: 'brandName', type: 'String' },
      { name: 'seriesId', type: 'Long' },
      { name: 'seriesName', type: 'String' },
      { name: 'typeId', type: 'Long' },
      { name: 'typeName', type: 'String' },
      { name: 'makerId', type: 'Long' },
      { name: 'makerName', type: 'String' },
      { name: 'warehouseId', type: 'Long' },
      { name: 'price', type: 'BigDecimal' },
      { name: 'discount', type: 'BigDecimal' },
      { name: 'requestQty', type: 'Integer' },
      { name: 'approveQty', type: 'Integer' },
      { name: 'outQty', type: 'Integer' },
      { name: 'stockRecordId', type: 'Long' },
      { name: 'remark', type: 'String' },
    ],
  },
  {
    resource: 'message',
    name: '消息通知表',
    group: '库存业务',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'type', type: 'Integer' },
      { name: 'userId', type: 'Long' },
      { name: 'message', type: 'String' },
      { name: 'sourceId', type: 'Long' },
      { name: 'isRead', type: 'Integer' },
      { name: 'state', type: 'Integer' },
    ],
  },
  {
    resource: 'user',
    name: '用户表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'username', type: 'String' },
      { name: 'deptId', type: 'Long' },
      { name: 'password', type: 'String' },
      { name: 'salt', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'phone', type: 'String' },
      { name: 'avatar', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'role',
    name: '角色表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'code', type: 'String' },
      { name: 'remark', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'permission',
    name: '权限表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'code', type: 'String' },
      { name: 'module', type: 'String' },
      { name: 'type', type: 'Integer' },
      { name: 'parentId', type: 'Long' },
      { name: 'path', type: 'String' },
      { name: 'sort', type: 'Integer' },
      { name: 'icon', type: 'String' },
      { name: 'component', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'userRole',
    name: '用户角色关系表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'userId', type: 'Long' },
      { name: 'roleId', type: 'Long' },
    ],
  },
  {
    resource: 'rolePermission',
    name: '角色权限关系表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'roleId', type: 'Long' },
      { name: 'permissionId', type: 'Long' },
    ],
  },
  {
    resource: 'userToken',
    name: '用户登录状态表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'token', type: 'String' },
      { name: 'userId', type: 'Long' },
      { name: 'loginTime', type: 'LocalDateTime' },
      { name: 'expireTime', type: 'LocalDateTime' },
      { name: 'loginIp', type: 'String' },
      { name: 'status', type: 'Integer' },
    ],
  },
  {
    resource: 'config',
    name: '系统配置表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'name', type: 'String' },
      { name: 'group', type: 'String' },
      { name: 'title', type: 'String' },
      { name: 'tip', type: 'String' },
      { name: 'type', type: 'String' },
      { name: 'value', type: 'String' },
      { name: 'content', type: 'String' },
    ],
  },
  {
    resource: 'operateLog',
    name: '操作日志表',
    group: '系统管理',
    fields: [
      { name: 'id', type: 'Long' },
      { name: 'userId', type: 'Long' },
      { name: 'username', type: 'String' },
      { name: 'module', type: 'String' },
      { name: 'operation', type: 'String' },
      { name: 'method', type: 'String' },
      { name: 'requestUrl', type: 'String' },
      { name: 'requestIp', type: 'String' },
      { name: 'requestParam', type: 'String' },
      { name: 'responseData', type: 'String' },
      { name: 'status', type: 'Integer' },
      { name: 'errorMsg', type: 'String' },
      { name: 'costTime', type: 'Integer' },
    ],
  },
];

export const CRUD_MODULE_MAP = CRUD_MODULES.reduce(
  (acc, module) => {
    const schema = CRUD_RESOURCE_SCHEMA_MAP[module.resource];
    acc[module.resource] = {
      ...module,
      tableFields: schema?.tableFields || module.fields,
      searchFields: schema?.searchFields || module.fields,
    };
    return acc;
  },
  {} as Record<string, CrudModule>,
);
